DROP SEQUENCE USER_DETAILS_SEQ_ID_SEQ;
DROP SEQUENCE order_order_id_seq ;
DROP SEQUENCE order_items_order_item_id_seq;
DROP SEQUENCE product_product_id_seq ;
DROP SEQUENCE user_details_seq_id_seq;

DROP TABLE cart CASCADE CONSTRAINTS;
DROP TABLE "ORDER" CASCADE CONSTRAINTS;
DROP TABLE order_items CASCADE CONSTRAINTS;
DROP TABLE product CASCADE CONSTRAINTS;
DROP TABLE "USER_DETAILS" CASCADE CONSTRAINTS;

-- Generated by Oracle SQL Developer Data Modeler 19.4.0.350.1424
--   at:        2022-12-02 02:33:42 CET
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g



CREATE TABLE cart (
    user_details_seq_id  INTEGER NOT NULL,
    cart_id              NUMBER NOT NULL
);

ALTER TABLE cart ADD CONSTRAINT cart_pk PRIMARY KEY ( cart_id );

CREATE TABLE cart_item (
    cart_item_id  INTEGER NOT NULL,
    created_date  DATE NOT NULL,
    quantity      INTEGER,
    product_id    NUMBER,
    cart_cart_id  NUMBER NOT NULL
);

ALTER TABLE cart_item ADD CONSTRAINT cart_item_pk PRIMARY KEY ( cart_item_id );

CREATE TABLE myorder (
    order_id             INTEGER NOT NULL,
    created_date         DATE,
    total_price          NUMBER,
    session_id           VARCHAR2(20),
    user_details_seq_id  INTEGER NOT NULL
);

ALTER TABLE myorder ADD CONSTRAINT myorder_pk PRIMARY KEY ( order_id );

CREATE TABLE order_items (
    order_item_id     INTEGER NOT NULL,
    quantity          INTEGER,
    price             NUMBER,
    created_date      DATE,
    myorder_order_id  INTEGER NOT NULL,
    product_id        NUMBER
);

ALTER TABLE order_items ADD CONSTRAINT order_items_pk PRIMARY KEY ( order_item_id );

CREATE TABLE product (
    product_id  INTEGER NOT NULL,
    name        VARCHAR2(255),
    price       NUMBER
);

ALTER TABLE product ADD CONSTRAINT product_pk PRIMARY KEY ( product_id );

CREATE TABLE user_details (
    seq_id      INTEGER NOT NULL,
    username    VARCHAR2(50),
    first_name  VARCHAR2(50),
    last_name   VARCHAR2(50),
    email       VARCHAR2(20),
    role        VARCHAR2(10),
    password    VARCHAR2(20)
);

ALTER TABLE user_details ADD CONSTRAINT user_details_pk PRIMARY KEY ( seq_id );

ALTER TABLE cart_item
    ADD CONSTRAINT cart_item_cart_fk FOREIGN KEY ( cart_cart_id )
        REFERENCES cart ( cart_id );

ALTER TABLE cart
    ADD CONSTRAINT cart_user_details_fk FOREIGN KEY ( user_details_seq_id )
        REFERENCES user_details ( seq_id );

ALTER TABLE myorder
    ADD CONSTRAINT myorder_user_details_fk FOREIGN KEY ( user_details_seq_id )
        REFERENCES user_details ( seq_id );

ALTER TABLE order_items
    ADD CONSTRAINT order_items_myorder_fk FOREIGN KEY ( myorder_order_id )
        REFERENCES myorder ( order_id );

CREATE SEQUENCE cart_user_details_seq_id_seq START WITH 1 NOCACHE ORDER;

CREATE OR REPLACE TRIGGER cart_user_details_seq_id_trg BEFORE
    INSERT ON cart
    FOR EACH ROW
    WHEN ( new.user_details_seq_id IS NULL )
BEGIN
    :new.user_details_seq_id := cart_user_details_seq_id_seq.nextval;
END;
/

CREATE SEQUENCE cart_cart_id_seq START WITH 1 NOCACHE ORDER;

CREATE OR REPLACE TRIGGER cart_cart_id_trg BEFORE
    INSERT ON cart
    FOR EACH ROW
    WHEN ( new.cart_id IS NULL )
BEGIN
    :new.cart_id := cart_cart_id_seq.nextval;
END;
/

CREATE SEQUENCE cart_item_cart_item_id_seq START WITH 1 NOCACHE ORDER;

CREATE OR REPLACE TRIGGER cart_item_cart_item_id_trg BEFORE
    INSERT ON cart_item
    FOR EACH ROW
    WHEN ( new.cart_item_id IS NULL )
BEGIN
    :new.cart_item_id := cart_item_cart_item_id_seq.nextval;
END;
/

CREATE SEQUENCE myorder_order_id_seq START WITH 1 NOCACHE ORDER;

CREATE OR REPLACE TRIGGER myorder_order_id_trg BEFORE
    INSERT ON myorder
    FOR EACH ROW
    WHEN ( new.order_id IS NULL )
BEGIN
    :new.order_id := myorder_order_id_seq.nextval;
END;
/

CREATE SEQUENCE order_items_order_item_id_seq START WITH 1 NOCACHE ORDER;

CREATE OR REPLACE TRIGGER order_items_order_item_id_trg BEFORE
    INSERT ON order_items
    FOR EACH ROW
    WHEN ( new.order_item_id IS NULL )
BEGIN
    :new.order_item_id := order_items_order_item_id_seq.nextval;
END;
/

CREATE SEQUENCE product_product_id_seq START WITH 1 NOCACHE ORDER;

CREATE OR REPLACE TRIGGER product_product_id_trg BEFORE
    INSERT ON product
    FOR EACH ROW
    WHEN ( new.product_id IS NULL )
BEGIN
    :new.product_id := product_product_id_seq.nextval;
END;
/

CREATE SEQUENCE user_details_seq_id_seq START WITH 1 NOCACHE ORDER;

CREATE OR REPLACE TRIGGER user_details_seq_id_trg BEFORE
    INSERT ON user_details
    FOR EACH ROW
    WHEN ( new.seq_id IS NULL )
BEGIN
    :new.seq_id := user_details_seq_id_seq.nextval;
END;
/



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                             6
-- CREATE INDEX                             0
-- ALTER TABLE                             10
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           7
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          7
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
